/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/signup2`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/InitialScreen/InitialScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MainScreen/MainScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SettingsScreen/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpS1/SignUpS1`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpS2/SignUpS2`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpScreen/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WelcomeScreen/WelcomeScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/signup2`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/InitialScreen/InitialScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginScreen/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/MainScreen/MainScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SettingsScreen/SettingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SignUpS1/SignUpS1`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SignUpS2/SignUpS2`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SignUpScreen/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/WelcomeScreen/WelcomeScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/signup2${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/InitialScreen/InitialScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/MainScreen/MainScreen${`?${string}` | `#${string}` | ''}` | `/screens/SettingsScreen/SettingsScreen${`?${string}` | `#${string}` | ''}` | `/screens/SignUpS1/SignUpS1${`?${string}` | `#${string}` | ''}` | `/screens/SignUpS2/SignUpS2${`?${string}` | `#${string}` | ''}` | `/screens/SignUpScreen/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/screens/WelcomeScreen/WelcomeScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/signup2`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/InitialScreen/InitialScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MainScreen/MainScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SettingsScreen/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpS1/SignUpS1`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpS2/SignUpS2`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpScreen/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WelcomeScreen/WelcomeScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
